jobs:
  playwright-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Install allurectl
        uses: allure-framework/setup-allurectl@v1

      - name: Create env file
        run: |
          touch .env
          echo WEBHOOK_URL=${{ secrets.WEBHOOK_URL }} >> .env
          echo "The .env file has been created:"
          cat .env

      - name: Run Playwright Tests with Allure Monitoring
        id: run_tests
        run: allurectl watch -- npx playwright test | tee allure_output.log

      - name: Extract Allure Report URL
        id: extract_url
        run: |
          echo "Extracting Allure report URL..."
          REPORT_URL=$(grep -o 'https://[^ ]*allure[^ ]*' allure_output.log | tail -n 1)
          echo "ALLURE_REPORT_URL=$REPORT_URL" >> $GITHUB_ENV
          echo "ALLURE_REPORT_URL=$REPORT_URL" >> .env
          echo "Allure Report URL: $REPORT_URL"

      - name: Debug .env
        run: cat .env
